import type { NavItem } from '../types/dashboard';
import type { WidgetMap } from '../widgets/types';

export const businessReportLayoutRows = [
  'AAABBBCCCDDD',
  'AAABBBCCCDDD',
  'EEEEFFFFGGGG',
  'EEEEFFFFGGGG',
  'HHHHIIIIJJJJ',
  'HHHHIIIIJJJJ',
  'KKKKLLLLMMMM',
  'KKKKLLLLMMMM',
];

const businessReportWidgets: WidgetMap = {
  A: {
    type: 'MetricValueWidget',
    visualType: 'metric-card',
    dataPolicy: 'static',
    displayTitle: '营业收入',
    titlePills: [
      { id: 'month', label: '本月' },
      { id: 'target', label: '目标' },
      { id: 'yoy', label: '同比' },
    ],
    bodySummary: '结论：收入保持稳健增长，线上直营和华东区域贡献最突出。',
    auxMetrics: [
      { label: '上期', value: '119,860,000' },
      { label: '目标', value: '135,000,000' },
      { label: '单位', value: '元' },
    ],
    props: {
      value: 128063459,
      unit: '元',
      yearOverYear: '+12.6%',
      monthOverMonth: '+4.8%',
      maxDecimals: 0,
    },
  },
  B: {
    type: 'MetricValueWidget',
    visualType: 'metric-card',
    dataPolicy: 'static',
    displayTitle: '经营利润',
    titlePills: [
      { id: 'profit', label: '利润' },
      { id: 'margin', label: '毛利' },
      { id: 'cost', label: '费用' },
    ],
    bodySummary: '结论：利润增速高于收入增速，费用率下降带动盈利改善。',
    auxMetrics: [
      { label: '上期', value: '21,940,000' },
      { label: '目标', value: '26,000,000' },
      { label: '单位', value: '元' },
    ],
    props: {
      value: 24860000,
      unit: '元',
      yearOverYear: '+15.2%',
      monthOverMonth: '+6.1%',
      maxDecimals: 0,
    },
  },
  C: {
    type: 'UniversalCardWidget',
    visualType: 'text-summary',
    dataPolicy: 'static',
    displayTitle: '目标达成',
    titlePills: [
      { id: 'actual', label: '实际' },
      { id: 'target', label: '目标' },
      { id: 'gap', label: '差距' },
    ],
    bodySummary: '结论：整体达成率为86%，利润达成较好，收入端仍有冲刺空间。',
    props: {
      cardKind: 'target',
      value: '86',
      unit: '%',
      target: '135,000,000元',
      status: '128,063,459元',
      gap: '6,936,541元',
      rows: [
        { label: '目标', value: '1.35亿' },
        { label: '当前', value: '1.28亿' },
        { label: '差距', value: '693.65万', tone: 'warning' },
      ],
      displayBudget: {
        rowHeightPx: 32,
        visibleRowCount: 3,
        maxVisibleItems: 3,
        overflowStrategy: 'show target, current, gap and achievement progress in one compact report card',
      },
    },
  },
  D: {
    type: 'RankingCardWidget',
    visualType: 'ranking-list',
    dataPolicy: 'static',
    displayTitle: '区域收入排名',
    titlePills: [
      { id: 'region', label: '区域' },
      { id: 'amount', label: '收入' },
      { id: 'growth', label: '增速' },
    ],
    bodySummary: '结论：华东保持第一，海外市场增速最快，华北需要补齐转化缺口。',
    auxMetrics: [
      { label: 'Top1', value: '25.5%' },
      { label: '对象', value: '5' },
      { label: '单位', value: '元' },
    ],
    props: {
      valueUnit: '元',
      displayBudget: {
        rowHeightPx: 32,
        visibleRowCount: 5,
        maxVisibleItems: 5,
        overflowStrategy: 'show top 5 operating regions with medal rank colors',
      },
      items: [
        { rank: 1, label: '华东大区', value: 32680000 },
        { rank: 2, label: '线上渠道', value: 28460000 },
        { rank: 3, label: '华南大区', value: 21930000 },
        { rank: 4, label: '海外市场', value: 18750000 },
        { rank: 5, label: '华北大区', value: 15320000 },
      ],
    },
  },
  E: {
    type: 'TemplateEChartWidget',
    visualType: 'line',
    dataPolicy: 'static',
    displayTitle: '收入利润趋势',
    titlePills: [
      { id: 'revenue', label: '收入' },
      { id: 'profit', label: '利润' },
      { id: 'forecast', label: '预测' },
    ],
    bodySummary: '结论：近6个月收入持续上行，利润曲线稳定改善。',
    auxMetrics: [
      { label: '峰值', value: '12806' },
      { label: '低值', value: '8740' },
      { label: '单位', value: '万元' },
    ],
    props: {
      chartKind: 'line',
      seriesName: '营业收入',
      unit: '万元',
      categories: ['1月', '2月', '3月', '4月', '5月', '6月'],
      values: [8740, 9320, 10180, 10890, 11986, 12806],
      tone: 'primary',
    },
  },
  F: {
    type: 'TemplateEChartWidget',
    visualType: 'pie',
    dataPolicy: 'static',
    displayTitle: '渠道收入结构',
    titlePills: [
      { id: 'channel', label: '渠道' },
      { id: 'share', label: '占比' },
      { id: 'growth', label: '增长' },
    ],
    bodySummary: '结论：线上直营占比最高，经销渠道保持稳定，门店增长恢复。',
    auxMetrics: [
      { label: '最大', value: '42%' },
      { label: '渠道', value: '4' },
      { label: '单位', value: '%' },
    ],
    props: {
      chartKind: 'pie',
      seriesName: '渠道收入',
      unit: '%',
      pieData: [
        { name: '线上直营', value: 42 },
        { name: '门店零售', value: 31 },
        { name: '经销渠道', value: 18 },
        { name: '工程客户', value: 9 },
      ],
      tone: 'primary',
    },
  },
  G: {
    type: 'TemplateEChartWidget',
    visualType: 'scatter',
    dataPolicy: 'static',
    displayTitle: '客户价值象限',
    titlePills: [
      { id: 'value', label: '价值' },
      { id: 'growth', label: '成长' },
      { id: 'risk', label: '风险' },
    ],
    bodySummary: '结论：高价值高成长客户集中在右上象限，需优先保障供给和服务。',
    auxMetrics: [
      { label: '样本', value: '6' },
      { label: '重点', value: '3' },
      { label: '单位', value: '分' },
    ],
    props: {
      chartKind: 'scatter',
      seriesName: '客户分群',
      unit: '分',
      points: [
        { name: '战略客户', value: [86, 88, 30] },
        { name: '成长客户', value: [72, 81, 24] },
        { name: '效率客户', value: [68, 62, 18] },
        { name: '观察客户', value: [45, 48, 12] },
        { name: '潜力客户', value: [57, 74, 20] },
        { name: '风险客户', value: [52, 31, 14] },
      ],
      tone: 'primary',
    },
  },
  H: {
    type: 'AdvancedEChartWidget',
    visualType: 'heatmap',
    dataPolicy: 'static',
    displayTitle: '费用与利润热力',
    titlePills: [
      { id: 'quarter', label: '季度' },
      { id: 'cost', label: '费用' },
      { id: 'profit', label: '利润' },
    ],
    bodySummary: '结论：Q3费用压力最高，Q4利润热度回升，需要继续压降营销投放偏差。',
    auxMetrics: [
      { label: '峰值', value: '91' },
      { label: '异常', value: '1' },
      { label: '单位', value: '分' },
    ],
    props: {
      chartKind: 'heatmap',
      seriesName: '经营热力',
      unit: '分',
    },
  },
  I: {
    type: 'AdvancedEChartWidget',
    visualType: 'radar',
    dataPolicy: 'static',
    displayTitle: '经营健康度',
    titlePills: [
      { id: 'health', label: '健康' },
      { id: 'ability', label: '能力' },
      { id: 'risk', label: '风险' },
    ],
    bodySummary: '结论：增长、盈利和现金表现较好，库存周转仍是主要短板。',
    auxMetrics: [
      { label: '最高', value: '91' },
      { label: '最低', value: '64' },
      { label: '单位', value: '分' },
    ],
    props: {
      chartKind: 'radar',
      seriesName: '经营健康度',
      unit: '分',
      radarIndicators: [
        { name: '增长', max: 100 },
        { name: '盈利', max: 100 },
        { name: '现金', max: 100 },
        { name: '库存', max: 100 },
        { name: '风险', max: 100 },
      ],
      radarValues: [88, 91, 83, 64, 72],
    },
  },
  J: {
    type: 'UniversalCardWidget',
    visualType: 'text-summary',
    dataPolicy: 'static',
    displayTitle: '异常预警',
    titlePills: [
      { id: 'risk', label: '风险' },
      { id: 'reason', label: '原因' },
      { id: 'owner', label: '责任' },
    ],
    bodySummary: '结论：逾期金额超过预警上限，需要本周完成客户回款复核。',
    props: {
      cardKind: 'warning',
      riskLevel: '高风险',
      metricName: '逾期金额',
      value: '245',
      unit: '万',
      target: '150万',
      gap: '+63%',
      status: '163%',
      rows: [
        { label: '较上月', value: '+63%', tone: 'danger' },
        { label: '预警上限', value: '150万' },
        { label: '触发规则', value: '超过上限', tone: 'danger' },
      ],
      displayBudget: {
        rowHeightPx: 32,
        visibleRowCount: 3,
        maxVisibleItems: 3,
        overflowStrategy: 'show high risk level, overdue amount, explanation metrics and over-limit progress',
      },
    },
  },
  K: {
    type: 'StatusRowsWidget',
    visualType: 'operational-list',
    dataPolicy: 'static',
    displayTitle: '重点行动清单',
    titlePills: [
      { id: 'all', label: '全部' },
      { id: 'doing', label: '推进' },
      { id: 'risk', label: '风险' },
    ],
    bodySummary: '结论：四项关键动作已明确责任人，回款和库存动作优先级最高。',
    props: {
      tone: 'primary',
      displayBudget: {
        rowHeightPx: 32,
        visibleRowCount: 5,
        maxVisibleItems: 5,
        overflowStrategy: 'show top 5 operating actions with compact adaptive rows',
      },
      items: [
        { label: '逾期客户回款复核', value: '今日闭环', status: 'danger' },
        { label: '华北门店转化提升', value: '推进中', status: 'warning' },
        { label: '高毛利新品补货', value: '已排产', status: 'success' },
        { label: '费用投放复盘', value: '本周完成', status: 'primary' },
        { label: '重点客户满意度回访', value: '已启动', status: 'success' },
      ],
    },
  },
  L: {
    type: 'UniversalCardWidget',
    visualType: 'funnel',
    dataPolicy: 'static',
    displayTitle: '商机转化漏斗',
    titlePills: [
      { id: 'lead', label: '线索' },
      { id: 'opp', label: '商机' },
      { id: 'deal', label: '成交' },
    ],
    bodySummary: '结论：线索到商机转化稳定，成交转化仍有约8个百分点提升空间。',
    auxMetrics: [
      { label: '转化', value: '33%' },
      { label: '流失', value: '440' },
      { label: '单位', value: '个' },
    ],
    props: {
      cardKind: 'funnel',
      rows: [
        { label: '有效线索', value: '1,280', percent: 100 },
        { label: '确认商机', value: '860', percent: 67 },
        { label: '成交订单', value: '420', percent: 33 },
      ],
      displayBudget: {
        rowHeightPx: 32,
        visibleRowCount: 3,
        maxVisibleItems: 3,
        overflowStrategy: 'show three key conversion stages with adaptive funnel chart',
      },
    },
  },
  M: {
    type: 'UniversalCardWidget',
    visualType: 'text-summary',
    dataPolicy: 'static',
    displayTitle: '经营结论',
    titlePills: [
      { id: 'summary', label: '结论' },
      { id: 'proof', label: '依据' },
      { id: 'action', label: '动作' },
    ],
    props: {
      cardKind: 'summary',
      headline: '经营质量',
      value: '稳中向好',
      unit: '',
      rows: [
        { label: '收入同比提升', value: '12.6%', tone: 'primary' },
        { label: '利润率继续改善', value: '1.8pct', tone: 'primary' },
        { label: '回款风险需跟进', value: '本周闭环', tone: 'warning' },
      ],
      displayBudget: {
        rowHeightPx: 32,
        visibleRowCount: 3,
        maxVisibleItems: 3,
        overflowStrategy: 'show executive conclusion and three evidence/action bullets',
      },
    },
  },
};

const buildNavItem = (id: string, label: string, icon: NavItem['icon']): NavItem => ({
  id,
  label,
  icon,
  layoutRows: businessReportLayoutRows,
  widgets: businessReportWidgets,
});

export const businessReportNav: NavItem[] = [
  buildNavItem('dashboard', '经营总览', 'Gauge'),
  buildNavItem('revenue', '收入分析', 'BarChart3'),
  buildNavItem('profit', '利润分析', 'Factory'),
  buildNavItem('channel', '渠道客户', 'Network'),
  buildNavItem('risk', '风险预警', 'Settings'),
];
