import type { ReportTemplateDevelopmentStep } from '../types';

export const reportTemplateDevelopmentFlow: ReportTemplateDevelopmentStep[] = [
  {
    id: 'framework-template',
    label: '选择框架模板',
    description: '首先选择框架模板，确定导航、内容画布、筛选、工具栏、主题和整体运行壳层。',
    outputArtifact: 'frameworkId',
    gate: 'framework-exists',
  },
  {
    id: 'page-layout-config',
    label: '设计页面布局配置',
    description: '设计页面布局配置，确定设计尺寸、12列网格、行高、滚动策略、背景、分块位置和稳定 blockId。',
    requiredInputs: ['frameworkId'],
    outputArtifact: 'pageLayoutId + layoutRows + block ids',
    gate: 'page-layout-exists',
  },
  {
    id: 'block-layout-template',
    label: '选择分块布局模板',
    description: '基于页面布局配置中的分块尺寸选择分块布局模板，例如 AA、AABBB、AABBCC 等带槽位模板，并确认 1-1 标题区、1-2 胶囊按钮区、2-1 附加信息区、2-2 单位区、3 组件区、4 说明区。',
    requiredInputs: ['pageLayoutId', 'layoutRows', 'blueprint block size'],
    outputArtifact: 'blockLayoutTemplateMap + selectedBlockLayoutVueFile + componentSlotContracts',
    gate: 'asset-size-match',
  },
  {
    id: 'title-area-config',
    label: '配置标题区',
    description: '配置分块布局模板的 1-1 标题区，实现标题文本和标题样式。',
    requiredInputs: ['selectedBlockLayoutVueFile'],
    outputArtifact: 'titleAreaConfig',
    gate: 'title-area-configured',
  },
  {
    id: 'pill-area-config',
    label: '判断并配置胶囊按钮区',
    description: '判断是否需要 1-2 胶囊按钮区；需要则配置胶囊按钮、选中态和样式，不需要则记录不配置。',
    requiredInputs: ['selectedBlockLayoutVueFile', 'titleAreaConfig'],
    outputArtifact: 'pillAreaConfig or null',
    gate: 'pill-area-decision',
  },
  {
    id: 'aux-metric-area-config',
    label: '配置附加信息区',
    description: '配置 2-1 附加信息区，添加合适的信息并等距排布。',
    requiredInputs: ['selectedBlockLayoutVueFile'],
    outputArtifact: 'auxMetricAreaConfig',
    gate: 'aux-metric-area-configured',
  },
  {
    id: 'unit-area-config',
    label: '判断并配置单位区',
    description: '判断是否需要 2-2 单位区；需要则配置单位文本和样式，不需要则记录不配置。',
    requiredInputs: ['selectedBlockLayoutVueFile', 'auxMetricAreaConfig'],
    outputArtifact: 'unitAreaConfig or null',
    gate: 'unit-area-decision',
  },
  {
    id: 'component-content-area-template',
    label: '选择组件内容区模板或 ECharts 自开发',
    description: '基于分块布局模板中的 3 组件区槽位配置，从组件内容区模板中选择合适模板；如果没有合适模板，则使用 ECharts 自开发新的独立 Vue 组件内容区模板。1-1、1-2、2-1、2-2、4 区域必须留在分块布局模板层。',
    requiredInputs: ['selectedBlockLayoutVueFile', 'titleAreaConfig', 'pillAreaConfig', 'auxMetricAreaConfig', 'unitAreaConfig', 'componentSlots[].templateSlotId'],
    outputArtifact: 'componentContentAreaTemplateMap + componentContentAreaVueFileMap + echartsSelfDevelopedTemplateMap',
    gate: 'slot-contract + widget schema',
  },
  {
    id: 'summary-area-config',
    label: '配置说明区',
    description: '配置 4 说明区，添加合适的结论、说明或解释；不需要则记录不配置。',
    requiredInputs: ['selectedBlockLayoutVueFile', 'componentContentAreaTemplateMap'],
    outputArtifact: 'summaryAreaConfig or null',
    gate: 'summary-area-decision',
  },
];
